### ISSUE TITLE
RTX 3080 not support hevc?

### ISSUE THREAD

**Issue by rexq57** [moonlight-stream/moonlight-common-c#53] opened 2020-10-29 01:11 UTC
![5BA6470A-0ABC-45E1-A676-F9CE445B67BB](https://user-images.githubusercontent.com/27030121/97513069-27fc5780-19c6-11eb-99f9-2fdb1e11ddad.png)
I found that response.payload not include a string "sprop-parameter-sets=AAAAAU", so fail to set NegotiatedVideoFormat as  h265, even if it is forced to set, but h264 is ok.

**Comment by cgutman** [comment] 2020-10-29 01:27
Yes, that's because GeForce Experience doesn't support HEVC on RTX 3000 series cards due to a bug. Even if you force it to request HEVC, GFE will return an error.

Duplicate of https://github.com/moonlight-stream/moonlight-qt/issues/447

**Closed by cgutman** 2020-10-29 01:27 UTC
